# Cloudflare Pages 配置文件
name = "blog-app"
compatibility_date = "2024-12-22"
pages_build_output_dir = ".next"

# D1 数据库绑定
[[d1_databases]]
binding = "DB" # 在代码中通过 env.DB 访问
database_name = "blog-db"
database_id = "3dd242d5-f86b-4acb-83e8-04945a47a525"

